FORMAT: 1A

# Reward API

Pubpular mechanism that involves check-in and collection of rewards based on points

# POST /v1/checkin/{pub_id}

Check-in member to collect points and rewards [POST]

+ Parameters
    + pub_id (integer) - Mandatory

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.InRlc3Qi.PhmEzCqGW-wpzCXoqGGZGLLu-LN6YAd7DAwqR_Tw0M4

+ Response 204 (application/json)


        