FORMAT: 1A

# Pub API

Public API to query available pubs by predefined filter/sorting criteria

## Pubs Collection [/v1/pubs{?latitude,longitude,page,search_term,deal_only}]

### List closest pubs based on location [GET]

Return a paged response for closest pubs based on location

+ Parameters
    + latitude (decimal) - Mandatory
    + longitude (decimal) - Mandatory
    + page (integer) - starts from 1
    + search_term (string) - return pubs with names with partial match
    + deal_only (boolean) - either "t" or "f" 

+ Response 200 (application/json)

        [
            {
                "id": 12,
                "name": "Loof",
                "phone": "+65 6337 9416",
                "address": "331 North Bridge Road, 03-07 Odeon Towers Extension", // optional
                "district": "D8. Central - Little India", // optional
                "time_opens": "7pm",
                "time_closes": "2am",
                "no_of_reviews": 277,
                "reviews_rating": 4.7,
                "cover_picture_url": "https://cdn.pubpular.com/cover/loof.png",
                "images": [
                    "https://cdn.pubpular.com/pictures/loof-1.png",
                    "https://cdn.pubpular.com/pictures/loof-2.png"
                ],
                "deals": [
                    {
                        "id": 7999,
                        "title": "One for one for limited period only",
                        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
                        "fine_print": "- New customers only\n-Beers only\nMinimum spend $20"
                    }
                ]
            }
        ]
        