FORMAT: 1A

# Reward API

Pubpular mechanism that involves check-in and collection of rewards based on points

# POST /v1/checkin/{pub_id}

Check-in member to collect points and rewards [POST]

+ Parameters
    + pub_id (integer) - Mandatory

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.InRlc3Qi.PhmEzCqGW-wpzCXoqGGZGLLu-LN6YAd7DAwqR_Tw0M4

+ Response 204 (application/json)

# GET /v1/accumulated_points

Query accumulated reward points

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.InRlc3Qi.PhmEzCqGW-wpzCXoqGGZGLLu-LN6YAd7DAwqR_Tw0M4

+ Response 200 (application/json)

        {
            "accumulated_points": 20000
        }
        
# POST /v1/claim_a_deal{?deal_id}

Claim a deal using accumulated_points

+ Parameters
    + deal_id (integer) - Mandatory

+ Request (application/json)

    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.InRlc3Qi.PhmEzCqGW-wpzCXoqGGZGLLu-LN6YAd7DAwqR_Tw0M4

+ Response 204 (application/json)